Squashed commit of the following:
commit e49f8fa25e3a1aba441fa9b0c6b641cb72f4f24a
Merge: b0b3687 7150f4f
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 14:46:45 2025 +0700

    Merge branch 'main' of https://github.com/WDP301-SMMS/Backend into test

commit b0b3687c4ea205c592d4143da15778daef97ec55
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 14:45:28 2025 +0700

    chore: add toJson for medicalInventory

commit 707abae72e97cc8aff0b57a83a0f80dbf0c908d1
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 14:14:34 2025 +0700

    fix: swagger wrong api

commit d7a9d63f63090754686f54333800d25b9d67568a
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 14:03:34 2025 +0700

    chore: dynamic server url for swagger

commit 756c731a8f94b089b6787ab079f61da3a1a5be4e
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 13:38:56 2025 +0700

    fix: cors

commit d94f7c1d8f58466c3f61d626794e0474be929109
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 13:22:37 2025 +0700

    fix: wrong backend path in swagger

commit 962155a3f1a8ae6e2f9f3ad54bc36d93587f90a6
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 13:14:24 2025 +0700

    fix: cors test

commit fed6a397c5eecb13e1077a814b64b1fb226f6a4d
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 13:02:49 2025 +0700

    fix: cors

commit 04b073dae3bfbc7d5451373ce781733546bafb8e
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 12:38:49 2025 +0700

    fix: cross origin

commit 7a375a030c343afcd93b7b02099b66dd0d35d9b2
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 12:32:49 2025 +0700

    fix: The operand of a 'delete' operator must be optional

commit d37772c16c4c0e6023da2b8c96eeb0fbeec4e45b
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 12:30:40 2025 +0700

    fix: error TS2790: The operand of a 'delete' operator must be optional.

commit 81f95c8e945c6269a6e79a4a3443c8e8e67dfca5
Author: Khai_Tran <tranmaiquangkhai@gmail.com>
Date:   Wed Jul 16 12:20:56 2025 +0700

    fix: cannot start server after build